parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Repository/Filter/'
            - '../src/Entity/'
            - '../src/Kernel.php'
